### ISSUE TITLE
*-master-0 is tainted: host-cpu

### ISSUE THREAD

**Issue by eelgaev** [ocp-power-automation/ocp4-upi-kvm#25]
Hey,
For some reason after a while when the VMs created by this tool enter a paused state, and it's difficult to unpause the VMs when it happen.
when checking journalct I can see the following:
`2020-07-26 10:46:50.328+0000: 608622: warning : qemuDomainObjTaint:7652 : Domain id=3 name='eli-574d-master-0' uuid=db66b34c-08f1-41e5-a23b-d412819a39fc is tainted: host-cpu`
I suspect that this is happening because the CPUs are set to "host-passthrough" ?

**Comment by yussufsh** [comment]
We could make it configurable and optional to use guest cpu mode.
