### ISSUE TITLE
DNS entries for master and workers are FQDN in DNS zone files

### ISSUE THREAD

**Issue by bhaubeck** [ocp-power-automation/ocp4-upi-kvm#29]
after deployment, the entries for masters and workers in the forward and in the reverse lookup zone are the FQDN of the nodes. 

in these files 
/var/named/zonefile.db
/var/named/reverse.db

we had to correct these entries by removing the domain part. 
these are the corrected lines: 

``
; Create entries for the master hosts
master-0	IN	A	192.168.88.4
master-1	IN	A	192.168.88.5
master-2	IN	A	192.168.88.6
;
; Create entries for the worker hosts
worker-0	IN	A	192.168.88.11
worker-1	IN	A	192.168.88.12
worker-2	IN	A	192.168.88.13
worker-3	IN	A	192.168.88.14
`

`

**Comment by yussufsh** [comment]
Thanks for reporting this. I will try to fix this one.
