### ISSUE TITLE
registry.terraform.io/community-terraform-providers/ignition 2.1.1 is not available for linux_ppc64le

### ISSUE THREAD

**Issue by redmark-redhat** [ocp-power-automation/ocp4-upi-kvm#73]
Host RHEL 8.3
Repo branch release-4.6
Terraform v0.13.4
+ provider registry.terraform.io/dmacvicar/libvirt v1.0.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.0

The init fails with 

Error: Failed to install provider

Error while installing community-terraform-providers/ignition v2.1.1: provider
registry.terraform.io/community-terraform-providers/ignition 2.1.1 is not
available for linux_ppc64le

Plus still see the warnings

Warning: Interpolation-only expressions are deprecated

  on modules/5_install/install.tf line 45, in locals:
  45:         release_image_override  = var.enable_local_registry ? "${local.local_registry_ocp_image}" : var.release_image_override

**Comment by yussufsh** [comment]
Please follow https://github.com/ocp-power-automation/ocp4-upi-kvm/blob/release-4.6/docs/terraform-provider-build.md#on-ibm-power-systems for running the automation on Power machine.

**Comment by redmark-redhat** [comment]
Yes, I followed the steps. Do I need a extra path variable for the plugins?

[root@cpt-ppc-016 ~]# ls -lR $PLUGIN_PATH/registry.terraform.io/*
/root/.local/share/terraform/plugins/registry.terraform.io/dmacvicar:
total 0
drwxr-xr-x. 3 root root 19 Dec 15 09:13 libvirt

/root/.local/share/terraform/plugins/registry.terraform.io/dmacvicar/libvirt:
total 0
drwxr-xr-x. 3 root root 27 Dec 15 09:13 1.0.0

/root/.local/share/terraform/plugins/registry.terraform.io/dmacvicar/libvirt/1.0.0:
total 0
drwxr-xr-x. 2 root root 40 Dec 15 09:14 linux_ppc64le

/root/.local/share/terraform/plugins/registry.terraform.io/dmacvicar/libvirt/1.0.0/linux_ppc64le:
total 28656
-rwxr-xr-x. 1 root root 29341280 Dec 15 09:14 terraform-provider-libvirt

/root/.local/share/terraform/plugins/registry.terraform.io/hashicorp:
total 0
drwxr-xr-x. 3 root root 19 Dec 15 09:16 null

/root/.local/share/terraform/plugins/registry.terraform.io/hashicorp/null:
total 0
drwxr-xr-x. 3 root root 27 Dec 15 09:16 2.1.2

/root/.local/share/terraform/plugins/registry.terraform.io/hashicorp/null/2.1.2:
total 0
drwxr-xr-x. 2 root root 37 Dec 15 09:16 linux_ppc64le

/root/.local/share/terraform/plugins/registry.terraform.io/hashicorp/null/2.1.2/linux_ppc64le:
total 22896
-rwxr-xr-x. 1 root root 23445352 Dec 15 09:16 terraform-provider-null

/root/.local/share/terraform/plugins/registry.terraform.io/terraform-providers:
total 0
drwxr-xr-x. 3 root root 19 Dec 15 09:13 ignition

/root/.local/share/terraform/plugins/registry.terraform.io/terraform-providers/ignition:
total 0
drwxr-xr-x. 3 root root 27 Dec 15 09:13 2.1.0

/root/.local/share/terraform/plugins/registry.terraform.io/terraform-providers/ignition/2.1.0:
total 0
drwxr-xr-x. 2 root root 41 Dec 15 09:13 linux_ppc64le

/root/.local/share/terraform/plugins/registry.terraform.io/terraform-providers/ignition/2.1.0/linux_ppc64le:
total 25452
-rwxr-xr-x. 1 root root 26062584 Dec 15 09:15 terraform-provider-ignition

**Comment by yussufsh** [comment]
Okay I see it now.

Please rename the directory:
```
mv /root/.local/share/terraform/plugins/registry.terraform.io/terraform-providers/ /root/.local/share/terraform/plugins/registry.terraform.io/community-terraform-providers/ 
```

Thanks for reporting it. We will get the documentation corrected.

**Comment by redmark-redhat** [comment]
Thanks
