### ISSUE TITLE
FAILED - RETRYING: Approve Worker CSRs (1 retries left).

### ISSUE THREAD

**Issue by redmark-redhat** [ocp-power-automation/ocp4-upi-kvm#77]
I'm getting this error trying to install OCP 4.6 on a RHEL 8.3 KVM host. Libvert is 6.0.0.

BASTION_IMAGE=rhel-8.2-update-2-ppc64le-kvm.qcow2.   BUT I've also tried rhel-8.3-ppc64le-kvm.qcow2

RHCOS_RELEASE=4.6.8 BUT I've also tried 6.8.1

Any Thoughts?

Thank
-Ron

module.install.null_resource.install (remote-exec): FAILED - RETRYING: Approve Worker CSRs (1 retries left).
module.install.null_resource.install: Still creating... [1h52m11s elapsed]
module.install.null_resource.install: Still creating... [1h52m21s elapsed]
module.install.null_resource.install: Still creating... [1h52m31s elapsed]
module.install.null_resource.install: Still creating... [1h52m41s elapsed]
module.install.null_resource.install: Still creating... [1h52m51s elapsed]
module.install.null_resource.install: Still creating... [1h53m1s elapsed]
module.install.null_resource.install (remote-exec): fatal: [localhost]: FAILED! => {"attempts": 30, "changed": true, "cmd": "oc get csr -ojson | jq -r '.items[] | select(.status == {} ) | .metadata.name' | xargs -r oc adm certificate approve\n", "delta": "0:00:01.915613", "end": "2020-12-18 10:23:28.596531", "rc": 0, "start": "2020-12-18 10:23:26.680918", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

module.install.null_resource.install (remote-exec): PLAY RECAP *********************************************************************
module.install.null_resource.install (remote-exec): 192.168.88.21              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.22              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.23              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.24              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.25              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.26              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.27              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.28              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.29              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.3               : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.30              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.4               : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.5               : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.6               : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): localhost                  : ok=31   changed=24   unreachable=0    failed=1    skipped=10   rescued=0    ignored=0

Warning: Interpolation-only expressions are deprecated

  on modules/5_install/install.tf line 45, in locals:
  45:         release_image_override  = var.enable_local_registry ? "${local.local_registry_ocp_image}" : var.release_image_override

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

Error: error executing "/tmp/terraform_1073376346.sh": Process exited with status 2

**Comment by redmark-redhat** [comment]
I also tried a 4.5 deployment with the same results. So I guess the issue is not the ocp, rhcos related.

OCP_VERSION=4.5
RHCOS_RELEASE=4.5.4

**Comment by redmark-redhat** [comment]
Problem was due to slow disk performance where the libvirt file(s) resided.

**Comment by lukebrowning** [comment]
Should this issue be closed?

**Comment by redmark-redhat** [comment]
Once we move the libvirt images to NVMe storage the host(s) could complete the cluster deployment(s).
