### ISSUE TITLE
Add support to for rhcos_kernel_options in var.tfvars

### ISSUE THREAD

**Issue by chuempel** [ocp-power-automation/ocp4-upi-kvm#81]
It would be great if one could specify RHCOS kernel parameters in the var.tfvars file of the TF automation, for example to set the slub_max_order=0 kernel paramter on the RHCOS worker nodes.

Example:
rhcos_kernel_options: ["slub_max_order=0"]

**Comment by yussufsh** [comment]
You should be able to run the linked patch on existing clusters by tainting install resource and re-running apply after updating the rhcos_kernel_options variable.

```
terraform taint module.install.null_resource.install
terraform apply -var-file ...
```
